# 增强剪枝策略示例配置
# 展示如何使用 cosine + plateau 调度和 HardConcrete 温度退火

# 基础训练配置
num_epochs: 100
lr: 2e-4
batch_size: 64
gpus: [0]

# 增强的剪枝配置
use_pruning_loss: true
target_sparsity: 0.7
sparsity_warmup_epochs: 20
sparsity_schedule: "cosine_plateau"  # 新增：cosine + plateau 调度
min_sparsity: 0.0
lambda_pair: [1.0, 5.0]
original_ssl_num_params: 95000000

# Plateau 配置
plateau_start_ratio: 0.9  # 90% 训练步后开始 plateau 阶段

# 学习率退火配置
use_plateau_lr_decay: true
lr_decay_factor: 0.1  # plateau 阶段学习率衰减到 10%
min_lr_ratio: 0.01     # 最小学习率为初始学习率的 1%

# HardConcrete 温度退火配置（在模型定义中设置）
# min_temperature: 0.1
# temperature_decay: 0.95
# temperature_decay_freq: 100

# SWA 配置（在训练脚本中设置）
# swa_start_iter: 9000  # 90% 训练步后开始 SWA
# swa_update_freq: 10   # 每 10 步更新一次 SWA
