### train configuraton

exp_dir: exp/ECAPA_TDNN_GLOB_c512-ASTP-emb192-WavLM_Large_joint_ft-num_frms150-aug0.6-spTrue-saFalse-ArcMargin_intertopk_subcenter-SGD-epoch20
gpus: "[0,1,2,3,4,5,6,7]"
num_avg: 2
enable_amp: False # whether enable automatic mixed precision training
do_lm: False

seed: 42
num_epochs: 15
save_epoch_interval: 1 # save model every epoch
log_batch_interval: 100 # log every 100 batchs

dataloader_args:
  batch_size: 128 
  num_workers: 8
  pin_memory: False
  prefetch_factor: 8
  drop_last: True


dataset_args:
  # the sample number which will be traversed within one epoch, if the value equals to 0,
  # the utterance number in the dataset will be used as the sample_num_per_epoch.
  sample_num_per_epoch: 0
  shuffle: True
  shuffle_args:
    shuffle_size: 2500
  filter: True
  filter_args:
    min_num_frames: 50
    max_num_frames: 400
  resample_rate: 16000
  speed_perturb: False
  num_frms: 150
  aug_prob: 0.6 # prob to add reverb & noise aug per sample
  frontend: "huggingface" # fbank, s3prl
  huggingface_args:
    upstream_args:
      name: "wavlm_large"
      path_or_url: "/scratch/project_465002053/junyi/sv/wespeaker_dev/wespeaker_hubert/examples/voxceleb/v4_pruning/convert/wavlm_large.hf.pth"
      pruning_units: ""
    frozen: True
    frame_shift: 20
    frame_length: 20
  cmvn: True
  cmvn_args:
    norm_mean: True
    norm_var: False
  spec_aug: False
  spec_aug_args:
    num_t_mask: 1
    num_f_mask: 1
    max_t: 10
    max_f: 8
    prob: 0.6

model: SSL_BACKEND_MHFA # ECAPA_TDNN_GLOB_c512, ECAPA_TDNN_GLOB_c1024
model_init: null
model_args:
  feat_dim: -1
  head_nb: 64
  embed_dim: 256
  compression_dim: 128
  feature_grad_mult: 0.0
  nb_layer: 25

projection_args:
  project_type: "arc_margin_intertopk_subcenter" # add_margin, arc_margin, sphere, softmax, arc_margin_intertopk_subcenter
  scale: 32.0
  easy_margin: False

margin_scheduler: MarginScheduler
margin_update:
  initial_margin: 0.0
  final_margin: 0.2
  increase_start_epoch: 2
  fix_start_epoch: 5
  update_margin: True
  increase_type: "exp" # exp, linear

loss: CrossEntropyLoss
loss_args: {}

optimizer: AdamW
optimizer_args:
  # momentum: 0.9
  # nesterov: True
  weight_decay: 1.0e-11

scheduler: ExponentialDecrease
scheduler_args:
  initial_lr: 1.0e-3
  final_lr: 5.0e-4
  warm_up_epoch: 3
  warm_from_zero: True
